before_install:
  - sudo apt-get install clang
  - sudo apt-get install cmake
  - sudo apt-get install astyle

language: cpp

# Compiler selection
compiler:
  - clang

install:

script:
  - mkdir build
  - cd build
  - cmake -D ENABLE_ALL_TESTS=ON .. && make -j
  - ctest -R
  - make indent
  - git diff
