STRING(REPLACE "\n" ";" MLIBVERSION ${VERSION_TXT})

# Get the first line of VERSION
LIST(GET MLIBVERSION 0 MLIB_VERSION_VERSION)

# Remove unwanted text
STRING(REPLACE "Version ............ " "" MLIB_VERSION_VERSION ${MLIB_VERSION_VERSION})

# Split version in major, minor. and patch
STRING(REPLACE "." ";" MLIB_VERSION_VERSION_LIST ${MLIB_VERSION_VERSION})

# Get major, minor. and patch
LIST(GET MLIB_VERSION_VERSION_LIST 0 MLIB_VERSION_VERSION_MAJOR)
LIST(GET MLIB_VERSION_VERSION_LIST 1 MLIB_VERSION_VERSION_MINOR)
LIST(GET MLIB_VERSION_VERSION_LIST 2 MLIB_VERSION_VERSION_PATCH)

# Export the definitions
ADD_DEFINITIONS(-DMLIB_VERSION_VERSION=${MLIB_VERSION_VERSION})
ADD_DEFINITIONS(-DMLIB_VERSION_VERSION_MAJOR=${MLIB_VERSION_VERSION_MAJOR})
ADD_DEFINITIONS(-DMLIB_VERSION_VERSION_MINOR=${MLIB_VERSION_VERSION_MINOR})
ADD_DEFINITIONS(-DMLIB_VERSION_VERSION_PATCH=${MLIB_VERSION_VERSION_PATCH})
