STRING(REPLACE "\n" ";" NUMERIXVERSION ${VERSION_TXT})

# Get the first line of VERSION
LIST(GET NUMERIXVERSION 0 NUMERIX_VERSION_VERSION)

# Remove unwanted text
STRING(REPLACE "Version ............ " "" NUMERIX_VERSION_VERSION ${NUMERIX_VERSION_VERSION})

# Split version in major, minor. and patch
STRING(REPLACE "." ";" NUMERIX_VERSION_VERSION_LIST ${NUMERIX_VERSION_VERSION})

# Get major, minor. and patch
LIST(GET NUMERIX_VERSION_VERSION_LIST 0 NUMERIX_VERSION_VERSION_MAJOR)
LIST(GET NUMERIX_VERSION_VERSION_LIST 1 NUMERIX_VERSION_VERSION_MINOR)
LIST(GET NUMERIX_VERSION_VERSION_LIST 2 NUMERIX_VERSION_VERSION_PATCH)

# Export the definitions
ADD_DEFINITIONS(-DNUMERIX_VERSION_VERSION=${NUMERIX_VERSION_VERSION})
ADD_DEFINITIONS(-DNUMERIX_VERSION_VERSION_MAJOR=${NUMERIX_VERSION_VERSION_MAJOR})
ADD_DEFINITIONS(-DNUMERIX_VERSION_VERSION_MINOR=${NUMERIX_VERSION_VERSION_MINOR})
ADD_DEFINITIONS(-DNUMERIX_VERSION_VERSION_PATCH=${NUMERIX_VERSION_VERSION_PATCH})
