# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_7Z "")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_IFW "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TXZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENTS_ALL "")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_CREATE_DESKTOP_LINKS "exampleApp")
SET(CPACK_DMG_BACKGROUND_IMAGE "/Users/esenonfossiio/git/MLIB/mlib/packaging/packaging/dmg_background.png")
SET(CPACK_DMG_DS_STORE_SETUP_SCRIPT "/Users/esenonfossiio/git/MLIB/mlib/packaging/packaging/DS_Store.scpt")
SET(CPACK_DMG_VOLUME_NAME "exampleApp")
SET(CPACK_GENERATOR "DragNDrop")
SET(CPACK_INSTALL_CMAKE_PROJECTS "/Users/esenonfossiio/git/MLIB/mlib/packaging;Project;ALL;/")
SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_MODULE_PATH "")
SET(CPACK_NSIS_DISPLAY_NAME "Project")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "Project")
SET(CPACK_OSX_PACKAGE_VERSION "10.6")
SET(CPACK_OUTPUT_CONFIG_FILE "/Users/esenonfossiio/git/MLIB/mlib/packaging/CPackConfig.cmake")
SET(CPACK_PACKAGE_CONTACT "kracejic <kracejic@gmail.com>")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/Users/esenonfossiio/git/MLIB/mlib/packaging/readme.md")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Clean cpp project. This is simple cpp example project build with CMake.")
SET(CPACK_PACKAGE_DIRECTORY "/Users/esenonfossiio/git/MLIB/mlib/packaging/out")
SET(CPACK_PACKAGE_EXECUTABLES "exampleApp;My Example Executable")
SET(CPACK_PACKAGE_FILE_NAME "Project-0.1.1-Darwin")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "Project")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Project")
SET(CPACK_PACKAGE_NAME "Project")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "kracejic")
SET(CPACK_PACKAGE_VERSION "0.1.1")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "1")
SET(CPACK_PACKAGING_INSTALL_PREFIX "/")
SET(CPACK_RESOURCE_FILE_LICENSE "/Users/esenonfossiio/git/MLIB/mlib/packaging/license.md")
SET(CPACK_RESOURCE_FILE_README "/opt/local/share/cmake-3.6/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/opt/local/share/cmake-3.6/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_7Z "")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/esenonfossiio/git/MLIB/mlib/packaging/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_TBZ2 "ON")
SET(CPACK_SOURCE_TGZ "ON")
SET(CPACK_SOURCE_TXZ "ON")
SET(CPACK_SOURCE_TZ "ON")
SET(CPACK_SOURCE_ZIP "OFF")
SET(CPACK_STRIP_FILES "TRUE")
SET(CPACK_SYSTEM_NAME "Darwin")
SET(CPACK_TOPLEVEL_TAG "Darwin")
SET(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/esenonfossiio/git/MLIB/mlib/packaging/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
