name: Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

permissions:
  contents: read

jobs:
  build-linux:

    name: Linux MLIB
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: modules
      run: |
        sudo apt-get update
        sudo apt-get install -yq --no-install-recommends numdiff

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D ENABLE_ALL_TESTS=ON

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: CPP Test
      working-directory: ${{github.workspace}}/build
      run: make run_tests

    - name: Python Test
      working-directory: ${{github.workspace}}
      run: source ${{github.workspace}}/scripts/run_pytest.sh

    - name: archive error 1
      uses: actions/upload-artifact@v3
      if: always()
      continue-on-error: true
      with:
        name: linux-CMakeOutput.log
        path: ${{github.workspace}}/build/CMakeFiles/CMakeOutput.log

    - name: archive error 2
      uses: actions/upload-artifact@v3
      if: always()
      continue-on-error: true
      with:
        name: linux-CMakeError.log
        path: ${{github.workspace}}/build/CMakeFiles/CMakeError.log
