name: windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

permissions:
  contents: read

jobs:
  build-windows:

    name: Windows MLIB
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]

    steps:
    - uses: actions/checkout@v3
    - name: info
      run: |
        cmake --version
        cmake -h
        wmic logicaldisk get size, freespace, caption

    - name: configure
      shell: bash
      run: |
        cmake -B D:\\a\\mlib\\mlib\\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D ENABLE_ALL_TESTS=ON
        cmake --build D:\\a\\mlib\\mlib\\build --config ${{env.BUILD_TYPE}}
    - name: archive logs
      uses: actions/upload-artifact@v3
      with:
        name: windows-detailed.log
        path: build/detailed.log
    - name: test library
      shell: bash
      run: |
        cmake --build build  --target test -- -m

    - name: archive error 1
      uses: actions/upload-artifact@v3
      if: always()
      continue-on-error: true
      with:
        name: windows-CMakeOutput.log
        path: D:\\a\\mlib\\mlib\\build\\CMakeFiles\\CMakeOutput.log

    - name: archive error 2
      uses: actions/upload-artifact@v3
      if: always()
      continue-on-error: true
      with:
        name: windows-CMakeError.log
        path: D:\\a\\mlib\\mlib\\build\\CMakeFiles\\CMakeError.log
